export const GET_LISTS_STARTED = 'GET_LISTS_STARTED'
export const GET_LISTS_SUCCESS = 'GET_LISTS_SUCCESS'
export const GET_LISTS_FAILURE = 'GET_LISTS_FAILURE'

export const CREATE_LIST = 'CREATE_LIST'
export const UPDATE_LIST = 'UPDATE_LIST'
export const DELETE_LIST = 'DELETE_LIST'
export const SET_CURRENT_LIST = 'SET_CURRENT_LIST'
