export const GET_TODOS_STARTED = 'GET_TODOS_STARTED'
export const GET_TODOS_SUCCESS = 'GET_TODOS_SUCCESS'
export const GET_TODOS_FAILURE = 'GET_TODOS_FAILURE'

export const UPDATE_TODO = 'UPDATE_TODO'
export const CREATE_TODO = 'CREATE_TODO'
export const DELETE_TODO = 'DELETE_TODO'
export const SORT_TODOS = 'SORT_TODOS'
export const CHANGE_LIST = 'CHANGE_LIST'
